/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedActivationsRouteImport } from './routes/_authenticated/activations'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedScreenshotsRouteImport } from './routes/_authenticated/screenshots'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivationsRoute =
  AuthenticatedActivationsRouteImport.update({
    id: '/activations',
    path: '/activations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScreenshotsRoute =
  AuthenticatedScreenshotsRouteImport.update({
    id: '/screenshots',
    path: '/screenshots',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/activations': typeof AuthenticatedActivationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/screenshots': typeof AuthenticatedScreenshotsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
}
export interface FileRoutesByTo {
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/activations': typeof AuthenticatedActivationsRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/screenshots': typeof AuthenticatedScreenshotsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRoute
  '/auth': typeof AuthRoute
  '/_authenticated/activations': typeof AuthenticatedActivationsRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/screenshots': typeof AuthenticatedScreenshotsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/auth'
    | '/activations'
    | '/logs'
    | '/screenshots'
    | '/settings'
    | '/vault'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activate'
    | '/auth'
    | '/activations'
    | '/logs'
    | '/screenshots'
    | '/settings'
    | '/vault'
    | '/workflows'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/activate'
    | '/auth'
    | '/_authenticated/activations'
    | '/_authenticated/logs'
    | '/_authenticated/screenshots'
    | '/_authenticated/settings'
    | '/_authenticated/vault'
    | '/_authenticated/workflows'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activations': {
      id: '/_authenticated/activations'
      path: '/activations'
      fullPath: '/activations'
      preLoaderRoute: typeof AuthenticatedActivationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/screenshots': {
      id: '/_authenticated/screenshots'
      path: '/screenshots'
      fullPath: '/screenshots'
      preLoaderRoute: typeof AuthenticatedScreenshotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivationsRoute: typeof AuthenticatedActivationsRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedScreenshotsRoute: typeof AuthenticatedScreenshotsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivationsRoute: AuthenticatedActivationsRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedScreenshotsRoute: AuthenticatedScreenshotsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
