/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ActivateRouteImport } from './routes/activate'
import { Route as ActivateDriverRouteImport } from './routes/activate.$driver'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin.accounts'
import { Route as AuthenticatedAdminActivationsRouteImport } from './routes/_authenticated/admin.activations'
import { Route as AuthenticatedAdminCardsRouteImport } from './routes/_authenticated/admin.cards'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminScreenshotsRouteImport } from './routes/_authenticated/admin.screenshots'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin.tasks'
import { Route as AuthenticatedAdminWorkflowsRouteImport } from './routes/_authenticated/admin.workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateRoute = ActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivateDriverRoute = ActivateDriverRouteImport.update({
  id: '/$driver',
  path: '/$driver',
  getParentRoute: () => ActivateRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/admin/accounts',
    path: '/admin/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminActivationsRoute =
  AuthenticatedAdminActivationsRouteImport.update({
    id: '/admin/activations',
    path: '/admin/activations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCardsRoute = AuthenticatedAdminCardsRouteImport.update({
  id: '/admin/cards',
  path: '/admin/cards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminScreenshotsRoute =
  AuthenticatedAdminScreenshotsRouteImport.update({
    id: '/admin/screenshots',
    path: '/admin/screenshots',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/admin/tasks',
  path: '/admin/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminWorkflowsRoute =
  AuthenticatedAdminWorkflowsRouteImport.update({
    id: '/admin/workflows',
    path: '/admin/workflows',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRouteWithChildren
  '/activate/$driver': typeof ActivateDriverRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/activations': typeof AuthenticatedAdminActivationsRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/screenshots': typeof AuthenticatedAdminScreenshotsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activate': typeof ActivateRouteWithChildren
  '/activate/$driver': typeof ActivateDriverRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/activations': typeof AuthenticatedAdminActivationsRoute
  '/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/screenshots': typeof AuthenticatedAdminScreenshotsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/activate': typeof ActivateRouteWithChildren
  '/activate/$driver': typeof ActivateDriverRoute
  '/admin/login': typeof AdminLoginRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/activations': typeof AuthenticatedAdminActivationsRoute
  '/_authenticated/admin/cards': typeof AuthenticatedAdminCardsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/screenshots': typeof AuthenticatedAdminScreenshotsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/workflows': typeof AuthenticatedAdminWorkflowsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activate'
    | '/activate/$driver'
    | '/admin/login'
    | '/admin/accounts'
    | '/admin/activations'
    | '/admin/cards'
    | '/admin/logs'
    | '/admin/screenshots'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/workflows'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activate'
    | '/activate/$driver'
    | '/admin/login'
    | '/admin/accounts'
    | '/admin/activations'
    | '/admin/cards'
    | '/admin/logs'
    | '/admin/screenshots'
    | '/admin/settings'
    | '/admin/tasks'
    | '/admin/workflows'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/activate'
    | '/activate/$driver'
    | '/admin/login'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/activations'
    | '/_authenticated/admin/cards'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/screenshots'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/workflows'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ActivateRoute: typeof ActivateRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate': {
      id: '/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof ActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activate/$driver': {
      id: '/activate/$driver'
      path: '/$driver'
      fullPath: '/activate/$driver'
      preLoaderRoute: typeof ActivateDriverRouteImport
      parentRoute: typeof ActivateRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/activations': {
      id: '/_authenticated/admin/activations'
      path: '/admin/activations'
      fullPath: '/admin/activations'
      preLoaderRoute: typeof AuthenticatedAdminActivationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cards': {
      id: '/_authenticated/admin/cards'
      path: '/admin/cards'
      fullPath: '/admin/cards'
      preLoaderRoute: typeof AuthenticatedAdminCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/screenshots': {
      id: '/_authenticated/admin/screenshots'
      path: '/admin/screenshots'
      fullPath: '/admin/screenshots'
      preLoaderRoute: typeof AuthenticatedAdminScreenshotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/admin/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/workflows': {
      id: '/_authenticated/admin/workflows'
      path: '/admin/workflows'
      fullPath: '/admin/workflows'
      preLoaderRoute: typeof AuthenticatedAdminWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminActivationsRoute: typeof AuthenticatedAdminActivationsRoute
  AuthenticatedAdminCardsRoute: typeof AuthenticatedAdminCardsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminScreenshotsRoute: typeof AuthenticatedAdminScreenshotsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminWorkflowsRoute: typeof AuthenticatedAdminWorkflowsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminActivationsRoute: AuthenticatedAdminActivationsRoute,
  AuthenticatedAdminCardsRoute: AuthenticatedAdminCardsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminScreenshotsRoute: AuthenticatedAdminScreenshotsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
  AuthenticatedAdminWorkflowsRoute: AuthenticatedAdminWorkflowsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ActivateRouteChildren {
  ActivateDriverRoute: typeof ActivateDriverRoute
}

const ActivateRouteChildren: ActivateRouteChildren = {
  ActivateDriverRoute: ActivateDriverRoute,
}

const ActivateRouteWithChildren = ActivateRoute._addFileChildren(
  ActivateRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ActivateRoute: ActivateRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
